# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = StuSys
DESTDIR = ./x64/Debug
CONFIG += debug
LIBS += -llibmysql
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(StuSys.pri)
win32:RC_FILE = StuSys.rc

FORMS += \
    insertdialog.ui

HEADERS += \
    insertdialog.h

SOURCES += \
    insertdialog.cpp
